services:
  postgres:
    image: postgres
#    volumes:
#      - ./prisma/migrations/20230307155656_init/migration.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "basistheory!"
    ports:
      - "5432:5432"